#!/bin/sh
###############################################################################
#                                                                             #
#   Filename        paths                                                     #
#                                                                             #
#   Description     Manage PATH variables                                     #
#                                                                             #
#   Notes                                                                     #
#                                                                             #
#   History                                                                   #
#    2019-09-17 JFL Created this script.                                      #
#    2020-11-24 JFL Use a shebang with the env command.                       #
#    2021-03-22 JFL Converted to a Posix shell script.                        #
#                                                                             #
#         © Copyright 2019 Hewlett Packard Enterprise Development LP          #
# Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
###############################################################################

# Global variables
VERSION="2021-03-22"
SCRIPT=`basename "$0"`	# Extract the script base name...

# Get the value of a variable.
VarValue() {
  eval "echo \"\${${1}}\""
}

#-----------------------------------------------------------------------------#
#                                                                             #
#   Function        Main                                                      #
#                                                                             #
#   Description     Process command line arguments                            #
#                                                                             #
#   Arguments       $*      Command line arguments                            #
#                                                                             #
#   Notes                                                                     #
#                                                                             #
#   History                                                                   #
#                                                                             #
#-----------------------------------------------------------------------------#

Help() {
  cat <<EOF
Paths variable manager

Usage: $SCRIPT [OPTIONS] [VARNAME]

Options:
  -?|-h|--help  Display this help
  -l|--list     List individual path components. (Default)

VarName: Paths variable name. Default: PATH
EOF
}

# Main routine
# Process command line arguments
VARNAME=PATH
ACTION=LIST

while [ $# -gt 0 ] ; do
  # Pop the first argument off the head of the list
  arg="$1"
  shift
  case "$arg" in
    -h|--help|"-?")
      Help
      exit 0
    ;;
    -l|--list)
      ACTION=LIST
    ;;
    -V|--version)
      echo $VERSION
      exit 0
    ;;
    -*)
      echo "Unrecognized option: \"$arg\"" >&2
      echo "Run $SCRIPT -? to get a list of valid arguments" >&2
      exit 1 ; # Unimplemented feature
    ;;
    *)
      VARNAME=$arg
    ;;
  esac
done

VALUE=`VarValue $VARNAME`
# Display each part in turn
IFS=:
set -o noglob # Avoid expanding * and ? in the value
for path in $VALUE'' ; do
  if [ -z "$path" -a "$VARNAME" = "PATH" ] ; then path=. ; fi # An empty path in $PATH is .
  if [ -n "$path" ] ; then echo "$path" ; fi
done

exit 0
