#!/bin/bash
###############################################################################
#                                                                             #
#   Filename        paths                                                     #
#                                                                             #
#   Description     Manage PATH variables                                     #
#                                                                             #
#   Notes                                                                     #
#                                                                             #
#   History                                                                   #
#    2019-09-17 JFL Created this script.                                      #
#                                                                             #
#         © Copyright 2019 Hewlett Packard Enterprise Development LP          #
# Licensed under the Apache 2.0 license - www.apache.org/licenses/LICENSE-2.0 #
###############################################################################

# Global variables
VERSION="2019-09-17"
ARGV=("$0" "$@")		# All arguments, as an array of strings
ARGV0="$0"                      # Full script pathname
SCRIPT="${ARGV0##*/}"           # Extract the script base name...
SCRIPTDIR="$(cd $(dirname "$0") ; /bin/pwd)" # ... and its absolute path
SCRIPTBASE="${SCRIPT%%.*}"	# Script base name without extension

#-----------------------------------------------------------------------------#
#                                                                             #
#   Function        Main                                                      #
#                                                                             #
#   Description     Process command line arguments                            #
#                                                                             #
#   Arguments       $*      Command line arguments                            #
#                                                                             #
#   Notes                                                                     #
#                                                                             #
#   History                                                                   #
#                                                                             #
#-----------------------------------------------------------------------------#

Help() {
  cat <<EOF
Paths variable manager

Usage: $SCRIPT [OPTIONS] [VARNAME]

Options:
  -?|-h|--help  Display this help
  -l|--list     List individual path components. (Default)

VarName: Paths variable name. Default: PATH
EOF
}

# Main routine
# Process command line arguments
VARNAME=PATH
ACTION=LIST

while (( $# > 0 )) ; do
  # Pop the first argument off the head of the list
  arg="$1"
  shift
  case "$arg" in
    -h|--help|"-?")
      Help
      exit 0
    ;;
    -l|--list)
      ACTION=LIST
    ;;
    -V|--version)
      echo $VERSION
      exit 0
    ;;
    -*)
      echo "Unrecognized option: \"$arg\"" >&2
      echo "Run $SCRIPT -? to get a list of valid arguments" >&2
      exit 1 ; # Unimplemented feature
    ;;
    *)
      VARNAME=$arg
    ;;
  esac
done

# Explode the PATH into a Bash array
IFS=':' read -r -a paths <<< "${!VARNAME}"

# Display each path in turn
for path in "${paths[@]}" ; do
    echo "$path"
done

exit 0
